### ISSUE TITLE
Is it more pythonic way to provide an option to load JSON file instead of table to opt out `load_table_data`

### ISSUE THREAD

**Issue by gmhhope** [cytoscape/py4cytoscape#121]
Hi Barry,

I am trying to show the p-values on the edge of the network. However, the p-value, since I haven't round it, is too long for visualization. 

Thus, I am trying to load a new column in the data table with rounded number of p-values, without regenerating the network... Then I found out, there is very limited option here if I don't regenerate the graph, which can be easily surpassed if automated customized figure embedding works :/ (#120). 

I liked the dictionary way to handle the data as there can be issue I previously mentioned, which turns NA into string and then the whole column become string type rather than float type. This solves perfectly when ship the whole network using cytoscape json data. 

Now that I cannot regenerate the graph, I want to just add a column in the table. Yet, it looks like I need to regenerate the table to `load_table_data_from_file`, which I also wanted to avoid in the 2nd paragraph. 

Maybe you have a cleverer idea to just turn the value to rounded/scientific notation? I will just manually do it but I really want to avoid this as my boss really wants to change the figure every day...

Thanks always for your support. I think I am now part of the super users in your tool. 

Thanks,
MG

**Comment by bdemchak** [comment]
Hi --

I'm not sure what you're asking for, exactly. Would you mind giving an example?

Thanks!

**Comment by gmhhope** [comment]
Busy with something else at this moment.
