### ISSUE TITLE
In version check, remove "-SNAPSHOT" when comparing versions

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/py4cytoscape#122]
To match RCy3 https://github.com/cytoscape/RCy3/commit/c3cafe4637b6f899f2bae0a91512d0955678e5f3, parse off -SNAPSHOT before doing a version comparison

**Comment by yihangx** [comment]
Also, we should match this: https://github.com/cytoscape/RCy3/commit/e8b6cb03eb9644f448c9041695d7d2aa8b06ccbc

check_supported_versions function should support version check like "3.10.2".

**Comment by bdemchak** [comment]
Done c62471a7581eb174e541f3aff9cec12a707afb35
