### ISSUE TITLE
INSTALL.rst

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/py4cytoscape#15]
```
cd py4cytoscape
python setup.py install # or python setup.py install --user
```

Report from other user: these steps don't appear to be required and setup.py is not found

**Comment by bdemchak** [comment]
Agreed. The installation section has been re-written to omit this instruction.

(Setup.py *is* required for pip to install py4cytoscape or to create the .whl for PyPI, so it remains in the repo.)
