### ISSUE TITLE
Add get_current_style

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/py4cytoscape#16]
Now supported by CyREST and being added to next release of RCy3:
https://github.com/cytoscape/RCy3/blob/master/R/Styles.R#L224

Note: the method returns _all_ values for the current style applied to a specified network (assuming one network view). In RCy3 I'm simply returning the title of the style as I think that is the primary use case for this method.

**Comment by bdemchak** [comment]
This was a duplicate. Merged new get_current_style() into 0.0.8 (from Master) and fixed a number of minor documentation and testing problems.
