### ISSUE TITLE
deprecation warning: pandas orient

### ISSUE THREAD

**Issue by jorgeboucas** [cytoscape/py4cytoscape#21]
```
/home/py4cy/.software_container/.python/3.9.0/lib/python3.9/site-packages/pandas-1.1.3-py3.9-linux-x86_64.egg/pandas/core/frame.py:1485: FutureWarning: Using short name for 'orient' is deprecated. Only the options: ('dict', list, 'series', 'split', 'records', 'index') will be used in a future version. Use one of the above to silence this warning.
  warnings.warn(
```

**Comment by bdemchak** [comment]
I'm a bit confused by this, and am a little surprised.

The Pandas document for 1.1.3 doesn't say anything about a deprecation. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html ... oddly, it looks like I'm way back on pandas 0.24.2, which is about 18 months old, but the document is current.

I do note that the examples in the documentation seem to omit the 'orient=' tag in calls like "cyedges.to_dict(orient='record')". That may be the ultimate fix for this warning.

Thinking further, it looks like you're running Python 3.9 ... mine is 3.7.9. Could this be a python deprecation, and if so, do you know exactly what's being deprecated and, maybe, where the deprecation is announced??

**Comment by jorgeboucas** [comment]
```

https://github.com/cytoscape/py4cytoscape/blob/ec0c2463e87f13cd8a52d03e6dac85219d75eeed/py4cytoscape/tables.py#L559
