### ISSUE TITLE
Add getCurrentStyle

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/py4cytoscape#22]
Add the getCurrentStyle function from RCy3 and update AutomationAPI. Make sure RCy3 advertises this AutomationAPI version.

**Comment by bdemchak** [comment]
See https://github.com/cytoscape/RCy3/commit/bde04cdf1d7af181ce81f549ffca8400aff66f46

**Comment by yihangx** [comment]
Fixed. Please double check and test it.

**Comment by bdemchak** [comment]
What tests did you add for this?

... sent from my mobile phone ... please forgive my typos.

**Comment by yihangx** [comment]
Give me a sec. I forgot to push test cases.
