### ISSUE TITLE
Sync with RCy3 getNetworkViewSUID refactor

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/py4cytoscape#24]
getNetworkViewSUID was rewritten in https://github.com/cytoscape/RCy3/commit/bde04cdf1d7af181ce81f549ffca8400aff66f46

**Comment by bdemchak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [py4cytoscape](https://trello.com/c/xyVEYXUY/8-py4cytoscape)

**Comment by yihangx** [comment]
Fixed. Please double check it and leave me some feedback.

**Comment by bdemchak** [comment]
What tests and additional tests verify your changes? ... I'm referring to
the test suites in the tests/ directory.

... sent from my mobile phone ... please forgive my typos.

**Comment by bdemchak** [comment]
Re-opened this pending discussion with Alex regarding reverting this. Reason: proposed implementation fundamentally changes semantics of function (i.e., accepting only network SUID instead of either network SUID or view SUID). Accepting this change would cause major version bump (e.g., py4cytoscape 1.0.0 instead of 0.0.8). Also, existing test fail with new implementation ... this must be resolved.
