### ISSUE TITLE
Match error handling messages for RCy3 StyleDefaults.R functions

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/py4cytoscape#25]
Minor wording changes for missing style name: https://github.com/cytoscape/RCy3/commit/bde04cdf1d7af181ce81f549ffca8400aff66f46

**Comment by bdemchak** [comment]
Also reword StyleDependencies.R error messages

**Comment by yihangx** [comment]
Fixed.

**Comment by yihangx** [comment]
Fixed.
