### ISSUE TITLE
Sync with new checks to filter processing in RCy3

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/py4cytoscape#26]
In applyFilter, createColumnFilter, createCompositeFilter, importFilters, and createDegreeFilter see checkSelected addition here: https://github.com/cytoscape/RCy3/commit/742db34a83d18e5289f7624366f9d7dc33b979fe

**Comment by AlexanderPico** [comment]
I added checkSelected to RCy3 based on how it was implemented in py4cy. So, I think this issue is resolved. @bdemchak

**Comment by bdemchak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [... [double click here] and choose GitHub PowerUp ...](https://trello.com/c/LgtcXEJC/9-double-click-here-and-choose-github-powerup)

**Comment by bdemchak** [comment]
Closed, per Alex implementing this in RCy3 https://github.com/cytoscape/RCy3/commit/742db34a83d18e5289f7624366f9d7dc33b979fe#diff-06e5cd3665f146cb1861ed3b2368fdb7ac0c78129fe816870dcc7fd66e201774
