### ISSUE TITLE
load_table_data funtion not work

### ISSUE THREAD

**Issue by yihangx** [cytoscape/py4cytoscape#28]
I am using Python to rewrite this R markdown(https://github.com/cytoscape/cytoscape-automation/blob/master/for-scripters/R/notebooks/Differentially-expressed-genes.Rmd). When I tried to run "p4c.load_table_data(de_genes_full, data_key_column='Gene', table_key_column='Entrez Gene')" , it raised CyError: In load_table_data(): Provided table key column "Entrez Gene" and data key column "Gene" do not contain any matches. In the same function in R file, "loadTableData(de.genes.full,data.key.column="Gene",table.key.column="Entrez Gene")" works with no error. I tried to debug and I found that the possible reason is in this line(https://github.com/cytoscape/py4cytoscape/blob/master/py4cytoscape/tables.py#L396), filter is always False because "[key in table_keys for key in data[data_key_column]]" in line 395 were in two different data types. Could you please try to run this and check it?

**Comment by bdemchak** [comment]
I see this issue, too. 

Specifically, map_table_column('display name', 'Human', 'HGNC', 'Entrez Gene') creates the 'Entrez Gene' column in the node table, and the data type is String.

I used Pandas' read_csv function to load the table data. It created the 'Gene' column as Int.

So, when you used load_table_data(de_genes_full, data_key_column='Gene', table_key_column='Entrez Gene'), it was trying to compare the string-typed 'Entrez Gene' column in the node table to the int-typed 'Gene' column in the Pandas table ... and was failing based on type mismatch.

The cheap way around this would be to set the 'Gene' data type when the CSV is read:

df.read_csv('https://raw.githubusercontent.com/cytoscape/cytoscape-tutorials/gh-pages/protocols/data/TCGA-Ovarian-MesenvsImmuno_data.csv', dtype={'Gene':str})

It sounds like you were expecting load_table_data in Python to work the same as loadTableData in R. This sounds right to me. To make this work, the list comprehension you identified in line 396 should be changed to compare string values, not direct values.

Do you agree?

**Comment by bdemchak** [comment]
Fixed via 14a4f76bb71aa6076696ab1732d0bc033fb4b2ec
