### ISSUE TITLE
get_edge_info does not accept list of SUIDs of edges

### ISSUE THREAD

**Issue by kozo2** [cytoscape/py4cytoscape#37]
The document says
```
get_edge_info(edges, network=None, base_url='http://127.0.0.1:1234/v1')[source]
Returns source, target and edge table row values.

Parameters
edges (list) – list of SUIDs or names of edges, i.e., values in the “name” column. Can also input single edge.
```

But actually it accepts **only** list of **names** of edges.

**Comment by bdemchak** [comment]
I have fixed this in my private build. It's really two problems, which we don't have answers to, yet.

You're right, though, that the documentation says that SUIDs should be accepted ... and that's now fixed and has a specific test.

The first related problem is that in RCy3, it appears that scalars are the same as lists. For example, 'ZYY023' is the same as ['ZYY023']. (True??) So, the RCy3 functions gracefully handle the case of a caller supplying either. In Python, they're not the same, so I have to have explicit checks for a scalar, and then upgrade the scalar to a list, and then go forward. (That's where today's bug was.)

The second related problem is some RCy3 functions are documented to accept a list of names, but they will likely accept a list of SUIDs, too. An example is getFirstNeighbors(). If you pass a list of SUIDs to py4cytoscape's get_first_neighbors(), an exception will likely be thrown.

So ... I think that for all functions, we should make a pass to identify which will accept either a list of names or a list of SUIDs ... and then document accordingly.

Also ... I think that for all functions that take a list of names or SUIDs, they can also take scalar name or SUID.

(This discussion is on our TODO list, and now it seems like we're having it.)

**Comment by AlexanderPico** [comment]
>The first related problem is that in RCy3, it appears that scalars are the same as lists.

True.

>The second related problem is some RCy3 functions are documented to accept a list of names, but they will likely accept a list of SUIDs, too.

True. For legacy reasons, I implemented names first and wrote the docs. Then I addes SUID support and didn't bother updating the docs :)  I'm happy to update the docs accordingly and participate in a check across all functions for consistency.

**Comment by bdemchak** [comment]
OK ... thanks, Alex ... very helpful.

So, that means that I need to address both, and be sure the test suite covers both, too. I'll do that in the next day or two.

**Comment by AlexanderPico** [comment]
Opened corresponding issue for RCy3: https://github.com/cytoscape/RCy3/issues/103

**Comment by bdemchak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [get_edge_info does not accept list of SUIDs of edges #36](https://trello.com/c/sy23dgPV/18-getedgeinfo-does-not-accept-list-of-suids-of-edges-36)

**Comment by bdemchak** [comment]
Fixed this and more in https://github.com/cytoscape/py4cytoscape/commit/cf156915bf96bf79cd28592085135bdf70b09bfe

For all functions (including get_edge_info) that accept a node list, they accept it as either a scalar (for a single node), a comma-separated list of node names, or a Python list. *And* they also accept a scalar (for a single SUID), a comma-separated list of SUIDs, or a Python list of SUIDs.

This also applies to group IDs in the group functions, as appropriate.

The documentation for each function was also updated.

Let me know if there are other issues like this.
