### ISSUE TITLE
Using basiCO to Run Reaction Kinetics Simulations on Py4cytoscape

### ISSUE THREAD

**Issue by kyxhik** [cytoscape/py4cytoscape#40]
Hello Barry, @bdemchak 

I am currently doing my Ph.D. in Computational Science at the University of Cape Town. My project is about developing systems biology tools for the modelling, simulation, and analysis of glycosylation networks found in Muc-1 type breast cancer tumours. 

Unlike many system biology tools on Cytoscape, I want to approach the network from an enzyme kinetics angle because glycosylation networks involve a lot of glycosyltransferases that determine the final structure of glycan chains.

I initially had a look at COPASI, a software application for simulation and analysis of biochemical networks, but found that it lacked features, such as automatic import and visualization of pathways from KEGG

My goal is to use Py4Cytoscape to call COPASI to implement mathematical modelling and time-course simulations on networks imported from KEGG.

I want to somehow create a bridge between basiCO, a simplified python interface for COPASI, and py4cytoscape.

This is where I got stuck.

One idea I had was to create a wrapper function that would take an imported network and do the following:

- pass its nodes as reacting species
- pass the edges as reactions with defined rate laws
- create an ODE model of the network
- Run simulations using basiCO
- Perturb the model by introducing enzyme inhibitors to it

Do you think writing a wrapper function could help to run basiCO on py4cytoscape? What other suggestions can you come up with?

I hope I made my problem clear. Let me know if you have any more questions and if you want to discuss this further.

Here is the detailed documentation of basiCO if you are interested: https://basico.readthedocs.io/en/latest/

All the best,

Emre

**Comment by bdemchak** [comment]
Hi, Emre ... thanks for you fabulous post! ... I have no problem with your ideas in principle, but will need a little bit of time to think about them in detail ... and look at the basiCO document. Please stand by.

**Comment by kyxhik** [comment]
Hello Barry!

Thank you for your response! Let's keep in touch for further discussion; I will continue brainstorming in the meantime.

All the best,

Emre

**Comment by bdemchak** [comment]
Hi, Emre ...

From what I can tell, COPASI is a desktop application written in C++ and running on a cross-platform GUI library. Good so far.

And it looks like basiCO extracts the computation portions of COPASI and incorporates it into a Python package ... there is no communication with COPASI, as basiCO appears to be completely self-contained.

Good for the COPASI architects ... sounds like they're doing a great job.

I think your idea is to use Cytoscape to load KEGG networks and make them available to basicCO. This seems very reasonable, with the following specifics:

* Cytoscape + browser (e.g., Chrome, Firefox) still needs to run on a desktop somewhere

* A KEGG app needs to be loaded into Cytoscape (using apps.cytoscape.org ... do a search for KEGG to see what matches your need. Note that not all apps are well supported ... the best ones tend to have high download counts)

* You create a Python program (e.g., Jupyter Notebook) that imports basiCO and py4cytoscape, and the app calls Cytoscape (via py4cytoscape) to load a network and then upload it into a Python iGraph or NetworkX, and then pass the network to basiCO ... you would know best how basiCO wants its data

Of course, there are variations on this. Note, too, that py4cytoscape can run in a cloud-based Notebook (e.g., Google Colab) and still access a desktop-based Cytoscape. (This is how I prefer to run it.)

You can get more information on py4cytoscape and network imports here: https://py4cytoscape.readthedocs.io/en/latest/reference/networks.html#module-py4cytoscape.networks

Does this match what you're thinking of??

**Comment by kyxhik** [comment]
Hi Barry!

Apologies for my late response. Your suggestion makes perfect sense, and that is the approach I am taking now.

I have been trying to figure out how to upload the network onto Python iGraph because I am getting a TypeError, but I found the line in the create_igraph_from_network function, where the error is originated.

I will post it in more details if I can't figure it out.

**Comment by kyxhik** [comment]
Hi Barry!

I hope you are doing great.

I was having issues with uploading the KEGG network to iGraph. Looking at the create_igraph_from_network, I found why I was getting TypeError or IndexError.

1- If the imported network has empty/undefined cells, py4cytoscape retrieves them as NaN or None, which is why the function generates a TypeError. This is because the function requires that the edge and node tables consist solely of string values.

2- If the edge name is not in the form "node1 (pp) node2", the source vs target dissection is generating an Index Error.

For example, the MUCIN-type Glycosylation Network that I imported from KEGG has edge names, such as rn:05915. That means x[1] does not exist, hence the IndexError below:

if not {'source', 'target'} <= set(cyedges.columns): 
        src_trg = [re.split("\ \\(.*\\)\ ", x) for x in cyedges['name']]      
        cyedges['source'] = [x[0] for x in src_trg] 
        cyedges['target'] = [x[1] for x in src_trg] 

Perhaps, this can be avoided by renaming the edges in the suitable format before creating source and target columns.

When it comes to the TypeError, I am not sure how to approach this. In my case, my network has one redundant edge that I can simply delete, but what happens if the node/edge tables have multiple empty columns?

**Comment by kyxhik** [comment]
I can perhaps create a pull request and add new features to the create_igraph_from_network function to make the any imported network more compatible with iGraph. What are your thoughts?

**Comment by bdemchak** [comment]
@kyxhik Hi ... sorry not to have seen this sooner. Would you like to create a pull request so I can take a look? The iGraph support has changed in 0.0.9 (and has been checked in for a while), but I doubt it handles this issue. Please post the PR when you're ready.
