### ISSUE TITLE
Text overlap inside node

### ISSUE THREAD

**Issue by rafael-diaz7** [cytoscape/py4cytoscape#57]
Happened randomly, wasn't happening before and label size does not affect it.
![Screenshot_11](https://user-images.githubusercontent.com/58955553/127454472-d8732839-8c31-416d-8044-de4d122f21bd.png)

**Comment by bdemchak** [comment]
Interesting ... thanks for this report. This wouldn't be a py4cytoscape issue, per-se ... it's a Cytoscape issue. Can you tell me which version of Cytoscape you're using? Cytoscape 3.9.0 is out in Beta ... would you be interesting in seeing if you can duplicate this? 

The Beta is here: https://cytoscape-builds.ucsd.edu/cytoscape-builds/Cytoscape-3.9.0/beta1/

(I'll leave this issue open for a while, hoping that it can be owned by Cytoscape.)

**Comment by bdemchak** [comment]
Thanks, Rafael …

 

Very useful information. Is there code you can share? We can say even more if we can reproduce the problem.

**Comment by rafael-diaz7** [comment]
Hey sorry for the late reply, been a bit busy, but sure thing! I have a bit of code. Obviously there's a lot more to the code, but this is where I call all the py4cytoscape commands. If there is more that needs to be seen, let me know - i'm sure we can figure something out.

   ```py
    start = time.time()  # tracking time for user purposes

    nodes = pd.read_csv(project_name + '_nodes.csv')
    edges = pd.read_csv(project_name + '_edges.csv')

    nodes['id'] = nodes.id.astype(str)
    nodes['font'] = nodes['size'].map(lambda x: x / 3)  # adding font sizes -> scale factor here
    nodes.at[len(nodes['id'].tolist()) - 1, 'name'] = 'root'  # change name of root for clearness

    # must be strings for cytoscape to read them in
    edges['source'] = edges['source'].astype(str)
    edges['target'] = edges['target'].astype(str)

    p4c.create_network_from_data_frames(nodes, edges, title="lbd_test", collection="tests")
    p4c.toggle_graphics_details()
    p4c.set_node_shape_default('ELLIPSE')  # default shape of ALL nodes - except root
    p4c.set_node_color_default('#00FF00')  # color should NOT appear
    p4c.set_node_size_mapping('id', nodes['id'].tolist(), nodes['size'].tolist(), mapping_type='d')
    p4c.set_node_font_size_mapping('id', nodes['id'].tolist(), nodes['font'].tolist(), mapping_type='d')
    p4c.set_edge_line_width_bypass(edges['name'].tolist(), edges['width'].tolist())
    p4c.set_edge_color_bypass(edges['name'].tolist(), edges['color'].tolist())
    p4c.set_node_shape_bypass(['root'], 'HEXAGON')  # root becomes hexagon
    p4c.set_node_color_bypass(['root'], '#FF0000')  # root becomes red

    end = time.time()  # end timer

    # timer information
    print("time taken in seconds:", end - start)
    print("time in minutes:", (end - start) / 60)
```

**Comment by bdemchak** [comment]
Thanks, Rafael ... I'll play with this a bit to see if I can duplicate this myself.

**Comment by rafael-diaz7** [comment]
And if this is any help, this is our table data so you can see what each column actually contains. There are various unnecessary columns, so I apologize if that creates an issue.

Nodes:
<img width="419" alt="image" src="https://user-images.githubusercontent.com/58955553/128559936-6e2a164f-33c7-4ab2-b673-d13e3cac6d1e.png">

Edges:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/58955553/128559966-20cf605b-96b8-41d6-b435-2887e87fe42e.png">

**Comment by bdemchak** [comment]
Very glad to have these ... they'll make my life easier. Looking at your code, I'm guessing there's a race condition somewhere deep in Cytoscape. I'll be very glad if I can reproduce it.

**Comment by bdemchak** [comment]
Hi, Rafael --

I have tried a couple of things, but haven't been able to reproduce this. I'm sending you my test files in case you can make this happen on your end. 

[test_rafael.zip](https://github.com/cytoscape/py4cytoscape/files/6958064/test_rafael.zip)

**Comment by rafael-diaz7** [comment]
I apologize for replying so late - got a burst of motivation. Unfortunately, I believe I have found the problem. It is not a py4cytoscape issue, so you were correct it is a Cytoscape issue. Once the font hits size 32768, the text begins going backwards. I'm not sure when it starts overlapping, but text starts to get a problem once it hits that size. Using a size of 32767 works perfectly fine however. Please refer to my screenshots, first screenshot is of 32767, second is of 32768
<img width="788" alt="image" src="https://user-images.githubusercontent.com/58955553/129149917-7fdb3243-9ecf-454a-b64e-8fce1d012409.png">
<img width="790" alt="image" src="https://user-images.githubusercontent.com/58955553/129150301-839c5875-c11d-408b-8dfd-6b8d8a34e7d3.png">

**Comment by bdemchak** [comment]
Great diagnostic work, Rafael ... thanks for your hard work!

Your conclusion has the ring of truth. I raised it at today's weekly developer meeting. The (unnamed) developers believe this is an undocumented feature, not a bug. :) Seriously, we believe this is an artifact of a deep Java class (e.g., Font) and there's not much we can do about it.
