### ISSUE TITLE
get_network_list() fails in local notebook

### ISSUE THREAD

**Issue by kozo2** [cytoscape/py4cytoscape#69]
This problem only occurs in local notebook, does not occur in Google Colab but it takes long time to get the result of the cell.

Try https://colab.research.google.com/github/cytoscape/py4cytoscape/blob/0.0.11/doc/tutorials/Cancer-networks-and-data.ipynb

![image](https://user-images.githubusercontent.com/12192/134052275-c14c1f86-9485-4d53-9410-e0fa58d4cdd3.png)

![image](https://user-images.githubusercontent.com/12192/134052317-2fb93887-75b5-44bc-a358-407f2a709469.png)

**Comment by bdemchak** [comment]
Agreed. The implementation of get_network_list in both RCy3 and py4cytoscape fetch the entire network, and then digs the network name out of that. And it does that for each existing network. 

I'll leave this open so we know to address this at some point ... though there's already a comment in the py4cyoscape code that points this out, too.

**Comment by bdemchak** [comment]
I think this is related to: https://github.com/cytoscape/py4cytoscape/issues/32

**Comment by bdemchak** [comment]
Solved by CyREST GET networks.names function
