### ISSUE TITLE
Verify that substantial remote workflow executes simultaneously for multiple users

### ISSUE THREAD

**Issue by bdemchak** [cytoscape/py4cytoscape#74]
Kozo's class was not able to execute a substantial workflow in a class full of users. It apparently hung.

**Comment by yihangx** [comment]
Can you elaborate the situation? I would like to help testing.

**Comment by bdemchak** [comment]
This appears to be the workflow: https://colab.research.google.com/drive/1OW9dUD5JOfcYJpiM2lyNIapJQHpKVJiZ#

According to reports at the time, it seems to be hanging around/before the loadTableData. 

The biggest problem is that the workflow is R, not Python. So, strictly speaking, it's not a py4cytoscape problem (so far). It could be an RCy3 problem or a Jupyter-Bridge problem. 

Does anyone know if there's a Python version? If so, I can pursue it.

**Comment by bdemchak** [comment]
This was solved in Juypyter-Bridge 0.0.4 ... many more threads were added, and a mutex was added just in case.
