### ISSUE TITLE
p4c.layout_network() ++

### ISSUE THREAD

**Issue by eirinland** [cytoscape/py4cytoscape#78]
Hello!
I can't figure out how (or if it is possible) to use use the Y files organic layout in my script as this is not one of the options for p4c.layout_network. 
Furthermore, does p4c offer a way of selecting isolated clusters in the network and annotating them? 
Any help with this is very much appreciated 🙏
Lastly, p4c would be even more amazing (love it already) if a function for creating legends from the mappings (that look nicer and is a bit more customisable than the ones generated by the legend creator app) was created!
Thanks for your great work, makes life easier for simple biochemists like me. 
Best regards, 
Eirin

**Comment by bdemchak** [comment]
Hi, Eirin --

Thanks for your very kind words! I'll answer as best I can.

Indeed, the yFiles layouts are very good. While we're very glad to have the yFiles layouts, they are licensed by their owner, yWorks, to Cytoscape under a special license that only covers GUI access. You might contact yWorks to see if it's possible to pay to access yFiles programatically.

Have you considered any of the Cytoscape-native layouts (e.g., Prefuse)? They're all available to py4cytoscape.

I have added a notation in the upcoming py4cytoscape v1.1.0 document to let future users know about this so they don't spend energy looking for yFiles functionality.

Regarding clustering, there are a number of Cytoscape apps that perform this, including MCode and ClusterMaker2. You can see examples of the use of each in https://github.com/bdemchak/cytoscape-jupyter/tree/main/gangsu ... and a section in the manual at https://py4cytoscape.readthedocs.io/en/latest/concepts.html#calling-cytoscape-apps

Did you know that you can execute Python/py4cytoscape in Google Colab? That's how the above workflows execute ... they contact the Cytoscape running on your workstation. This type of functionality works very well for publishing/sharing workflows. Feel free to ask more about this or the workflows themselves.

Regarding annotating clusters, there is an annotation API defined for py4cytoscape, but it's not implemented yet. I'm happy to prioritize this for your sake if you'd be interested in verifying that it'll serve your purpose, and then verify its operation once I implement it. Are you interested in this?

You raise an excellent point about the legend creator app. I checked with the authors, and they say that exposing it for automation (e.g., py4cytoscape) is several months away. They do appreciate the question, though, and I think it may influence their priorities.

Comments??
Feel free to steal from these

**Comment by eirinland** [comment]
Thanks for the great reply!
Yes, I have used the Prefuse layout. This results in node overlaps which does not occur with the yFiles layout. There is probably a simple way to avoid this, I just haven't figured it out yet. 

I will check out the clustering apps mentioned and see if they might aid me, thank you!
I will also check out the tutorials. 

It would be great to test the mentioned annotation API, I can however ofc do this manually for now if you have more pressing matters to take care of ☺️
I thought I should try to explain what I want to be able to do:
The networks I'm working with are "simple" Sequence similarity networks with the aim of discovering new interesting enzymatic candidates.
<img width="261" alt="Screenshot 2022-02-01 at 14 53 39" src="https://user-images.githubusercontent.com/90095974/151981090-78547169-30a6-4ed5-8a73-b1bf81735ab0.png">
Over is a small screenshot from one of the generated networks using our program. 
What I mean with annotating the clusters is basically selecting the isolated clusters (or part of one if that is doable) and giving them an appropriate label as shown in the figure (which is easy to do by hand, but not optimal time wise).
If it was possible to create annotated subnetworks from that selection aswell (as one also can do manually), that would be awesome. 
Hope that made sense!
Best regards,
Eirin

**Comment by eirinland** [comment]
I realised that I can just use the EFI-EST color SSN feature, and import the cluster numbers generated there and then use these with the CyREST API to use the Autoannotator from my script🙈
Thanks anyway! 
Best,
Eirin

**Comment by bdemchak** [comment]
Hi, Eirin –

 

Your annotation need should be fairly straightforward. I’m including (below) the API that RCy3 uses, but translated to what would probably be implemented in Python for py4cytoscape.

 

The API reflects the operations possible with the Cytoscape GUI … good as far as it goes. However, looking over the API, I see that the annotations are positioned in coordinates on the graph space. Fine, except that those positions aren’t sensitive to wherever the nodes and clusters end up because of the layout. I can imagine solutions to this, but I’d like to alert you so you can weigh in on the importance of the issue or palatable solutions.

 

Can you use these, and what of the positioning issue?

 

Summary

=======

 

function add_annotation_text(text = None, x_pos = None, y_pos = None,

                            font_size = None, font_family = None, font_style = None,

                            color = None, angle = None, name = None,

                            canvas = None, z_order = None,

                            network = None, base_url = DEFAULT_BASE_URL)

 

function add_annotation_bounded_text(text = None, x_pos = None, y_pos = None,

                            font_size = None, font_family = None, font_style = None,

                            color = None, angle = None, type = None,

                            custom_shape = None, fill_color = None, 

                            opacity = None, border_thickness = None,

                            border_color = None, border_opacity = None,

                            height = None, width = None,

                            name = None, canvas = None, z_order = None,

                            network = None, base_url = DEFAULT_BASE_URL)

 

function add_annotation_image(url = None, x_pos = None, y_pos = None,

                             angle = None, 

                             opacity = None, brightness = None,

                             contrast = None, border_thickness = None,

                             border_color = None, border_opacity = None,

                             height = None, width = None,

                             name = None, canvas = None, z_order = None,

                             network = None, base_url = DEFAULT_BASE_URL)

 

function add_annotation_shape(type = None, custom_shape = None, x_pos = None, y_pos = None,

                              angle = None, fill_color = None, 

                              opacity = None, border_thickness = None,

                              border_color = None, border_opacity = None,

                              height = None, width = None,

                              name = None, canvas = None, z_order = None,

                              network = None, base_url = DEFAULT_BASE_URL)

 

function delete_annotation<-function(names = None, base_url = DEFAULT_BASE_URL)

 

function get_annotation_list(network = None, base_url = DEFAULT_BASE_URL)

 

function ungroup_annotation(names = None, network = None, base_url = DEFAULT_BASE_URL)

 

function group_annotation(names = None, network = None, base_url = DEFAULT_BASE_URL)

 

function update_annotation_text(text = None, annotation_name = None, x_pos = None, y_pos = None,

                            font_size = None, font_family = None, font_style = None,

                            color = None, angle = None, name = None,

                            canvas = None, z_order = None,

                            network = None, base_url = DEFAULT_BASE_URL)

 

function update_annotation_bounded_text(text = None, annotation_name= None, x_pos = None, y_pos = None,

                                   font_size = None, font_family = None, font_style = None,

                                   color = None, angle = None, type = None,

                                   custom_shape = None, fill_color = None, 

                                   opacity = None, border_thickness = None,

                                   border_color = None, border_opacity = None,

                                   height = None, width = None,

                                   name = None, canvas = None, z_order = None,

                                   network = None, base_url = DEFAULT_BASE_URL)

 

function update_annotation_shape(type = None, custom_shape = None, annotation_name = None, x_pos = None, y_pos = None,

                             angle = None, fill_color = None, 

                             opacity = None, border_thickness = None,

                             border_color = None, border_opacity = None,

                             height = None, width = None,

                             name = None, canvas = None, z_order = None,

                             network = None, base_url = DEFAULT_BASE_URL)

 

function update_annotation_image(url = None, annotation_name = None, x_pos = None, y_pos = None,

                             angle = None, 

                             opacity = None, brightness = None,

                             contrast = None, border_thickness = None,

                             border_color = None, border_opacity = None,

                             height = None, width = None,

                             name = None, canvas = None, z_order = None,

                             network = None, base_url = DEFAULT_BASE_URL)

 

function update_group_annotation(name = None, annotation_name= None, x_pos = None, y_pos = None,

                                 angle = None, canvas = None, z_order = None,

                                 network= None, base_url = DEFAULT_BASE_URL)

 

 

 

Details

=======

 

function add_annotation_text(text = None, x_pos = None, y_pos = None,

                            font_size = None, font_family = None, font_style = None,

                            color = None, angle = None, name = None,

                            canvas = None, z_order = None,

                            network = None, base_url = DEFAULT_BASE_URL)

 

Adds a text annotation to a Cytoscape network view. The object will also be added to the 

 Annotation Panel in the GUI.

 

                text -- The text to be displayed

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                font_size -- (optional) Numeric value; default is 12

                font_family -- (optional) Font family; default is Arial

                font_style -- (optional) Font style; default is

                color -- (optional) Hexidecimal color; default is #000000 (black) angle (optional) 

                                Angle of text orientation; default is 0.0 (horizontal)

                name -- (optional) Name of annotation object; default is "Text"

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

returns -- A named list of annotation properties, including UUID

 

---------------------------------------------------------------------------------------

function add_annotation_bounded_text(text = None, x_pos = None, y_pos = None,

                            font_size = None, font_family = None, font_style = None,

                            color = None, angle = None, type = None,

                            custom_shape = None, fill_color = None, 

                            opacity = None, border_thickness = None,

                            border_color = None, border_opacity = None,

                            height = None, width = None,

                            name = None, canvas = None, z_order = None,

                            network = None, base_url = DEFAULT_BASE_URL)

 

Adds a bounded text annotation to a Cytoscape network view. The 

 object will also be added to the Annotation Panel in the GUI.

 

                text -- The text to be displayed

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                font_size -- (optional) Numeric value; default is 12

                font_family -- (optional) Font family; default is Arial

                font_style -- (optional) Font style; default is

                color -- (optional) Hexidecimal color; default is #000000 (black) angle (optional) 

                                Angle of text orientation; default is 0.0 (horizontal)

                angle -- (optional) Angle of text orientation; default is 0.0 (horizontal)

                type -- (optional) The type of the shape, default is RECTANGLE. 

                                See getNodeShapes() for valid options.

                custom_shape -- (optional) If a custom shape, this is the text of the shape

                fill_color -- (optional) Hexidecimal color; default is #000000 (black)

                opacity -- (optional) Opacity of fill color. Must be an integer between 0 and 100; default is 100.

                border_thickness -- (optional) Integer

                border_color -- (optional) Hexidecimal color; default is #000000 (black)

                border_opacity -- (optional) Integer between 0 and 100; default is 100.

                height -- (optional) Height of bounding shape; default is based on text height.

                width -- (optional) Width of bounding shape; default is based on text length.

                name -- (optional) Name of annotation object; default is "Text"

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

return -- A named list of annotation properties, including UUID

 

---------------------------------------------------------------------------------------

 

 

function add_annotation_image(url = None, x_pos = None, y_pos = None,

                             angle = None, 

                             opacity = None, brightness = None,

                             contrast = None, border_thickness = None,

                             border_color = None, border_opacity = None,

                             height = None, width = None,

                             name = None, canvas = None, z_order = None,

                             network = None, base_url = DEFAULT_BASE_URL)

                                                                                                                

 Adds a Image annotation to a Cytoscape network view. The object will also be added to 

 the Annotation Panel in the GUI.

 

                url -- URL or path to image file. File paths can be absolute or relative to current working directory. 

                                URLs must start with http:// or https://.

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                angle -- (optional) Angle of text orientation; default is 0.0 (horizontal)

                opacity -- (optional) Opacity of fill color. Must be an integer between 0 and 100; default is 100.

                brightness -- (optional) Image brightness. Must be an integer between 0 and 100; default is 100.

                contrast -- (optional) Image contrast. Must be an integer between 0 and 100; default is 100.

                border_thickness -- (optional) Integer

                border_color -- (optional) Hexidecimal color; default is #000000 (black)

                border_opacity -- (optional) Integer between 0 and 100; default is 100.

                height -- (optional) Height of image; default is based on text height.

                width -- (optional) Width of image; default is based on text length.

                name -- (optional) Name of annotation object; default is "Text"

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

return -- A named list of annotation properties, including UUID

 

---------------------------------------------------------------------------------------

 

function add_annotation_shape(type = None, custom_shape = None, x_pos = None, y_pos = None,

                              angle = None, fill_color = None, 

                              opacity = None, border_thickness = None,

                              border_color = None, border_opacity = None,

                              height = None, width = None,

                              name = None, canvas = None, z_order = None,

                              network = None, base_url = DEFAULT_BASE_URL)

 

Adds a shape annotation to a Cytoscape network view. The object will also be added to 

 the Annotation Panel in the GUI.

 

                type -- (optional) The type of the shape, default is RECTANGLE. See getNodeShapes() for valid options.

                custom_shape -- (optional) If a custom shape, this is the text of the shape

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                angle -- (optional) Angle of text orientation; default is 0.0 (horizontal)

                fill_color -- (optional) Hexidecimal color; default is #000000 (black)

                opacity -- (optional) Opacity of fill color. Must be an integer between 0 and 100; default is 100.

                border_thickness -- (optional) Integer

                border_color -- (optional) Hexidecimal color; default is #000000 (black)

                border_opacity -- (optional) Integer between 0 and 100; default is 100.

                height -- (optional) Height of image; default is based on text height.

                width -- (optional) Width of image; default is based on text length.

                name -- (optional) Name of annotation object; default is "Text"

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

return - A named list of annotation properties, including UUID

 

---------------------------------------------------------------------------------------

function delete_annotation<-function(names = None, base_url = DEFAULT_BASE_URL)

 

Remove an annotation from the current network view in Cytoscape

 

                names -- List of annotations by UUID or Name

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

return - None

 

---------------------------------------------------------------------------------------

 

 

function get_annotation_list(network = None, base_url = DEFAULT_BASE_URL)

 

A list of named lists with annotation information 

 

                network -- (optional) Name or SUID of the network. Default is the "current" network 

                                active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

return - RETURN_DESCRIPTION

 

---------------------------------------------------------------------------------------

 

function ungroup_annotation(names = None, network = None, base_url = DEFAULT_BASE_URL)

 

Ungroup annotation group from the network view in Cytoscape

                names -- Name of annotation group by UUID or Name

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

return - None

 

---------------------------------------------------------------------------------------

 

function group_annotation(names = None, network = None, base_url = DEFAULT_BASE_URL)

 

Group annotation from the network view in Cytoscape

 

                name -- Name of annotation by UUID or Name

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

return - None

 

---------------------------------------------------------------------------------------

 

function update_annotation_text(text = None, annotation_name = None, x_pos = None, y_pos = None,

                            font_size = None, font_family = None, font_style = None,

                            color = None, angle = None, name = None,

                            canvas = None, z_order = None,

                            network = None, base_url = DEFAULT_BASE_URL)

 

Updates a text annotation to a Cytoscape network view. The object 

 will also be added to the Annotation Panel in the GUI.

 

                text -- The text to be displayed

                annotation_name -- Name of annotation by UUID or Name

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                font_size -- (optional) Numeric value; default is 12

                font_family -- (optional) Font family; default is Arial

                font_style -- (optional) Font style; default is

                color -- (optional) Hexidecimal color; default is #000000 (black)

                angle -- (optional) Angle of text orientation; default is 0.0 (horizontal)

                name -- (optional) Name of annotation object; default is "Text"

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

 

return - A named list of annotation properties, including UUID

 

---------------------------------------------------------------------------------------

 

function update_annotation_bounded_text(text = None, annotation_name= None, x_pos = None, y_pos = None,

                                   font_size = None, font_family = None, font_style = None,

                                   color = None, angle = None, type = None,

                                   custom_shape = None, fill_color = None, 

                                   opacity = None, border_thickness = None,

                                   border_color = None, border_opacity = None,

                                   height = None, width = None,

                                   name = None, canvas = None, z_order = None,

                                   network = None, base_url = DEFAULT_BASE_URL)

 

Adds a bounded text annotation to a Cytoscape network view. The object will also be added 

 to the Annotation Panel in the GUI.

 

                text -- The text to be displayed

                annotation_name -- Name of annotation by UUID or Name

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                font_size -- (optional) Numeric value; default is 12

                font_family -- (optional) Font family; default is Arial

                font_style -- (optional) Font style; default is

                color -- (optional) Hexidecimal color; default is #000000 (black)

                type -- (optional) The type of the shape, default is RECTANGLE. See getNodeShapes() for valid options.

                angle -- (optional) Angle of text orientation; default is 0.0 (horizontal)

                custom_shape -- (optional) If a custom shape, this is the text of the shape

                fill_color -- (optional) Hexidecimal color; default is #000000 (black)

                opacity -- (optional) Opacity of fill color. Must be an integer between 0 and 100; default is 100.

                border_thickness -- (optional) Integer

                border_color -- (optional) Hexidecimal color; default is #000000 (black)

                border_opacity -- (optional) Integer between 0 and 100; default is 100.

                height -- (optional) Height of image; default is based on text height.

                width -- (optional) Width of image; default is based on text length.

                name -- (optional) Name of annotation object; default is "Text"

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

 

return - A named list of annotation properties, including UUID

  

---------------------------------------------------------------------------------------

 

function update_annotation_shape(type = None, custom_shape = None, annotation_name = None, x_pos = None, y_pos = None,

                             angle = None, fill_color = None, 

                             opacity = None, border_thickness = None,

                             border_color = None, border_opacity = None,

                             height = None, width = None,

                             name = None, canvas = None, z_order = None,

                             network = None, base_url = DEFAULT_BASE_URL)

 

Updates a shape annotation to a Cytoscape network view. The object will also be added to 

 the Annotation Panel in the GUI.

 

                type -- (optional) The type of the shape, default is RECTANGLE. See getNodeShapes() for valid options.

                custom_shape -- (optional) If a custom shape, this is the text of the shape

                annotation_name -- Name of annotation by UUID or Name

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                angle -- (optional) Angle of text orientation; default is 0.0 (horizontal)

                opacity -- (optional) Opacity of fill color. Must be an integer between 0 and 100; default is 100.

                border_thickness -- (optional) Integer

                border_color -- (optional) Hexidecimal color; default is #000000 (black)

                border_opacity -- (optional) Integer between 0 and 100; default is 100.

                height -- (optional) Height of image; default is based on text height.

                width -- (optional) Width of image; default is based on text length.

                name -- (optional) Name of annotation object; default is "Text"

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

  

return - A named list of annotation properties, including UUID

 

 

---------------------------------------------------------------------------------------

 

function update_annotation_image(url = None, annotation_name = None, x_pos = None, y_pos = None,

                             angle = None, 

                             opacity = None, brightness = None,

                             contrast = None, border_thickness = None,

                             border_color = None, border_opacity = None,

                             height = None, width = None,

                             name = None, canvas = None, z_order = None,

                             network = None, base_url = DEFAULT_BASE_URL)

 

Updates a Image annotation to a Cytoscape network view. The 

 object will also be added to the Annotation Panel in the GUI.

 

                url -- URL or path to image file. File paths can be absolute or relative to current working 

                                directory. URLs must start with http:// or https://.

                annotation_name -- Name of annotation by UUID or Name

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                angle -- (optional) Angle of text orientation; default is 0.0 (horizontal)

                opacity -- (optional) Opacity of fill color. Must be an integer between 0 and 100; default is 100.

                brightness -- (optional) Image brightness. Must be an integer between 0 and 100; default is 100.

                contrast -- (optional) Image contrast. Must be an integer between 0 and 100; default is 100.

                border_thickness -- (optional) Integer

                border_color -- (optional) Hexidecimal color; default is #000000 (black)

                border_opacity -- (optional) Integer between 0 and 100; default is 100.

                height -- (optional) Height of image; default is based on text height.

                width -- (optional) Width of image; default is based on text length.

                name -- (optional) Name of annotation object; default is "Text"

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network -- (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url -- (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

 

return - A named list of annotation properties, including UUID

  

 

---------------------------------------------------------------------------------------

 

function update_group_annotation(name = None, annotation_name= None, x_pos = None, y_pos = None,

                                 angle = None, canvas = None, z_order = None,

                                 network= None, base_url = DEFAULT_BASE_URL)

  

 Updates a group annotation, changing the given properties.

 

                name -- (optional) Name of annotation object

                annotation_name -- Name of annotation by UUID or Name

                x_pos -- (optional) X position in pixels from left; default is center of current view

                y_pos -- (optional) Y position in pixels from top; default is center of current view

                angle -- (optional) Angle of text orientation; default is 0.0 (horizontal)

                canvas -- (optional) Canvas to display annotation, i.e., foreground (default) or background 

                z_order -- (optional) Arrangement order specified by number (larger values are in front of 

                                smaller values); default is 0 

                network (optional) Name or SUID of the network. Default is the "current" network active in Cytoscape.

                base_url (optional) Ignore unless you need to specify a custom domain, port or version to connect 

                                to the CyREST API. Default is http://localhost:1234 and the latest version of the CyREST API 

                                supported by this version of py4cytoscape.

 

 

return - A named list of annotation properties, including UUID

**Comment by bdemchak** [comment]
Hi, Eirin –

 

That makes sense to me … and I think it solves my concern about the coordinates issue in RCy3’s APIs.

 

Do you agree?

 

I’ll be talking with the RCy3 people about this … 

 

Thanks!

**Comment by eirinland** [comment]
Hello again!
Yes, when doing it the way I described the result is:
<img width="502" alt="Screenshot 2022-02-04 at 10 53 47" src="https://user-images.githubusercontent.com/90095974/152508719-0258f2a3-e805-41be-ae8e-7280782f84cc.png">
Which was exactly how I wanted it and I have no issues with the positions for my use at least. 
I have to "hide shapes" manually in Cytoscape, but that is just pressing a single button, and the users might like to be able to tweak this small thing themselves. 
So, as long as a column for the cluster IDs can be obtained in some way (probably a cleaner way than the data merging and use of EFI-EST that I have been up to) running the Autoannotater from the script works neatly.

As for creating subnetworks, it is no problem using p4c.create_subnetwork by creating a column filter from the node cluster column and then nodes="selected". 

Best,
Eirin

**Comment by eirinland** [comment]
Hello again!
Sorry for taking up so much of your time, and thanks again for the great answers and inputs.
Regarding my last answer I noticed something really odd:
when running:
clusterfilter = p4c.create_column_filter('Clusterfilter', 'Cluster Number', Clusternumbers[0], "IS", True)
I see that not all the nodes which has "Cluster Number" =1 are selected. I naturally thought it was something wrong with the data in these particular nodes.
However, when I run it again, it is not the same nodes that are not selected:
First run:
<img width="390" alt="Screenshot 2022-02-04 at 11 59 57" src="https://user-images.githubusercontent.com/90095974/152517785-96de4501-9167-4da0-aeae-dec82e66e088.png">
Second run:
<img width="373" alt="Screenshot 2022-02-04 at 12 00 43" src="https://user-images.githubusercontent.com/90095974/152518000-1d4d65ec-d2f7-4f75-81d3-298eb3070c8f.png">

Have you ever seen this issue before?
Best,
Eirin

**Comment by bdemchak** [comment]
Excellent! Thanks for the report, and for the great tips on annotations.

 

Regarding your project, is there (or will there be) a citation we can use to reference it from one of our future papers?

**Comment by bdemchak** [comment]
Hi, Eirin –

 

Not at all … your questions are very valuable, and we’re very happy to have them.

 

Regarding the filtering, I think I saw this in older versions of Cytoscape. Which version are you running? 

 

If it’s not 3.9.0 or 3.9.1, would you consider upgrading?

 

If you’re already on a 3.9, would you mind putting this network into a .CYS file and making it available to us? Good to try this using our tools.

 

Thanks!

**Comment by eirinland** [comment]
Hello again!
Sorry for late reply.
I use Cytoscape 3.9.1.
As the file is rather large, maybe I could get an email to share a one drive folder with? 

I also notices another problem when I run the code all over again:



<img width="494" alt="Screenshot 2022-02-18 at 16 16 31" src="https://user-images.githubusercontent.com/90095974/154710102-c59e41e6-961f-40cb-8995-d2de5e2950af.png">

For some reason the clusters are no longer in the order of size, which makes it look slightly messy, and two annotation and cluster overlaps occurred..

When it comes to publication, that is probably a bit far in the future sadly, as a lot of wet lab work will follow this initial candidate mining.

Best,
Eirin

**Comment by eirinland** [comment]
Not sure if this is of any interest, but thought I might share anyway.
I believe I have fixed several of my problems by utilising the clustermaker "connectedcomponents" to create the column of cluster numbers. This way I avoid utilizing the EFI SSN utilities. 
This also seem to order the clusters nicely each time.

p4c.commands.commands_post("cluster connectedcomponents attribute=--None--")

#Auto annotate cannot use the numbers in the __ccCluster column as lables, because it is an integer. 
#Export the data and then load it into py so that i can manipulate it

import pandas as pd

df=p4c.get_table_columns(table="node", columns ="shared name, __ccCluster")
#Create a new column with "cluster #" as a string

Clusternumbers = df["__ccCluster"].unique().tolist()
list.sort(Clusternumbers)
Clusternumbersstring = [str(x) for x in Clusternumbers]
sizeoflist = len(Clusternumbers)
i=0

while i < sizeoflist:
    df.loc[df['__ccCluster'] == i+1 , 'Cluster Label'] = ('Cluster ' + Clusternumbersstring[i])
    i += 1

p4c.load_table_data(df, data_key_column="shared name")

#Run autoannotate to lable the clusters
p4c.commands.commands_post("autoannotate annotate-clusterBoosted clusterIdColumn=Cluster Label labelColumn=Cluster Label useClusterMaker=False")


Best,
Eirin

**Comment by eirinland** [comment]
Hello again! 
I have a new challenge I was wondering if you guys have a suggestion on how to solve.
Is there a way to switch from the edge table to node table with a python script?
I could not find a function that do this in p4cyto or cyREST.
Apparently, autoAnnotate need the node table to be the "selected" table in the graphical interface for it to work. But when I generate a new network with my script, the edge table is the default shown table. 

Any suggestions?
Best,
Eirin

**Comment by bdemchak** [comment]
Hi, Eirin --

Sorry for missing this question. It slipped by.

Using the GUI, I have loaded a network and selected the edge table. I then performed an AutoAnnotate. The annotation seems to have succeeded, even with the Edge Table selected. This is what I would expect.

Can you give an example of where this isn't working? If so, I can ask the group that created the AutoAnnotate app.

You're right, though, that there's no CyREST (or py4cytoscape) feature that selects one table tab or another.

Thanks!

**Comment by bdemchak** [comment]
Thanks, Eirin, for the code that puts a string-based cluster number in a table. It really shouldn't be this hard, but for now, I think you have it right. As a test, I tried using CyREST to create a new column (... it works ...) and then insert a formula (e.g., =TEXT($__ccCluster)). The formula text was inserted, but the formula wasn't evaluated. I would have expected the formula to be evaluated, thereby creating a string version of __ccCluster. But no. I have filed a bug report on this ... let's see what happens.

**Comment by bdemchak** [comment]
... closing this out ...

But as regards yFiles usage, note that there is a yFiles for Jupyter now, should you be interested in executing your workflow under Jupyter and then rendering in Jupyter instead of Cytoscape: https://pypi.org/project/yfiles-jupyter-graphs/

We haven't checked this out yet, but it looks promising!
