### ISSUE TITLE
Nodes size specification error

### ISSUE THREAD

**Issue by IlonaGA** [cytoscape/py4cytoscape#79]
Hello! I am trying to set different node sizes, but ``` In cyrest_get(): Could not serialize Mappings. ``` error appears.

Here is the code:
```
nodes = pd.read_csv('nodes_COAD.tsv', sep='\t')
edges = pd.read_csv('edges_COAD.tsv', sep='\t')

node_degree = pd.concat([edges['source'].value_counts(), edges['target'].value_counts()]) 
node_degree.rename('degree', inplace=True)
nodes = nodes.set_index('id').join(node_degree).reset_index()

p4c.create_network_from_data_frames(nodes, edges, title=project, collection="DataFrame Example")

p4c.set_node_size_mapping('id', nodes['id'].tolist(), nodes['degree'].tolist(), mapping_type='d')

p4c.notebook_export_show_image()
```
Do you have any ideas how to solve this issue?
Thank you!

**Comment by IlonaGA** [comment]
Hello, thank you for your answer. Files are not large, here is the link https://drive.google.com/drive/folders/1C7w9Np8xb2Uz3LPVoHEkpActxxeFA4Pg?usp=sharing

**Comment by bdemchak** [comment]
Hi, Alexandra ...

I'm not having any problem with your code ... it seems to work fine (except for the notebook_show_image(), which would be better as notebook_export_show_image()).

Can you tell me which version of py4cytoscape you're using? The current PyPI version is 0.0.11, which should be good enough.

I'm attaching two different versions of your code ... one as a Jupyter Notebook (launched from PyCharm on Windows) and the other running on Google Colab.

Here is the Colab version: https://colab.research.google.com/drive/1WBwSKJsks5YcYgVAWi2ZOsTGxrPzrz1t?usp=sharing 

(Did you know that you can execute a Notebook in the cloud and have it communicate with Cytoscape on your PC?? ... that's what the Colab does.)

I'm attaching the standalone Jupyter Notebook (as ZIP), which is probably more like what you're interested in.
[Alexandra.zip](https://github.com/cytoscape/py4cytoscape/files/8248975/Alexandra.zip)

The one possibility for problems that I can think of would be that sometimes py4cytoscape finishes a function before Cytoscape does ... meaning that the following function might fail. We try hard to make sure this never happens, but if that's happening, you can workaround by inserting time.sleep() between py4cytoscape function calls. 

Comments??

**Comment by IlonaGA** [comment]
Hello, sorry for the late answer, the problem was fixed by running script in Jupyter Notebook... 
Thank you!

**Comment by bdemchak** [comment]
Good ... thanks!
