### ISSUE TITLE
faster select_all_* functions

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/py4cytoscape#80]
Turns out this is really slow on large networks:
https://github.com/cytoscape/py4cytoscape/blob/master/py4cytoscape/network_selection.py#L493

Rather than collecting all edge SUIDs and then passing them to `select_edges`, you can simply use the CyCommands keyword, "all"

Same for `select_all_nodes`

And you can also add a `select_all` function that passes "all" for both lists in a single commandPost(), e.g., in RCy3 https://github.com/cytoscape/RCy3/blob/master/R/NetworkSelection.R#L77

**Comment by bdemchak** [comment]
Now matches RCy3: sped up select_all_*, added select_all

https://github.com/cytoscape/py4cytoscape/commit/36ad7c308a351f392dba0be6a90b6192b8ed214b
