### ISSUE TITLE
Customize the path of the detailed log file

### ISSUE THREAD

**Issue by agitter** [cytoscape/py4cytoscape#95]
Is it possible the change where the detailed log file is written?  If I found the right place in the source
https://github.com/cytoscape/py4cytoscape/blob/cc3186c722f2789460b90547105d7ffa87d0460f/py4cytoscape/py4cytoscape_logger_settings.py#L34-L35

it looks like this is hard-coded and cannot be modified.

**Comment by bdemchak** [comment]
Hi ... thanks for the suggestion, and I appreciate the time you took to track this down.

It's a pretty reasonable suggestion. Would it help for the path to be picked up from an environment variable? If so, I can make that change and check it into the 1.6.0 branch this morning (Pacific time). Otherwise, do you have a different suggestion?

Thanks.

**Comment by agitter** [comment]
Setting this path via an environment variable would be great. I ran into this when playing around with py4cytoscape inside a Singularity container where the default log path isn't writeable. I could easily set the path with an environment variable and would prefer that to the other workaround I have in place now.

Thanks for the very fast response!

**Comment by bdemchak** [comment]
Yes ... I figured. You're ahead of me with the Singularity/Docker stuff ... I'm happy for suggestions that will move you ahead faster. I have two things to clear off my desk, and then will work on this one. Thanks.

**Comment by bdemchak** [comment]
OK, agitter ... I have added parsing for the PY4CYTOSCAPE_DETAIL_LOGGER_DIR environment variable in the py4cytoscape_logger.py initialization. The directory is "logs" unless it's overridden in the environment. I tested on Windows 10, but not on *nix ... I don't expect any issues, though.

Also, I updated the logging documentation.

All of this is in the Github 1.6.0 branch, which is relatively stable, and may be released to PyPI next week.

See https://github.com/cytoscape/py4cytoscape/commit/7e889db4404c09f23284066c84a87a78790de684

Thanks for this great suggestion! Please let me know how this works for you.

**Comment by agitter** [comment]
Thanks @bdemchak!  I'll do my testing in an Ubuntu-based container and let you know if I run into any problems.  Looking at the commit, this looks perfect.

It may be a week or more before I get back to this though.

**Comment by bdemchak** [comment]
Wonderful... good luck!

... sent from my mobile phone ... please forgive my typos.

vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
: Barry Demchak, PhD                   :
: Torrey Pines Software, Inc.          :
: http://www.tpsoft.com/               :
: http://orcid.org/0000-0001-7065-7786 :
: (858) 452-8700                       :
: (619) 218-3717 (cell/text)           :
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
