### ISSUE TITLE
FutureWarning: in py4cytoscape\tables.py:502:

### ISSUE THREAD

**Issue by kozo2** [cytoscape/py4cytoscape#97]
```
c:\Users\kozo2\mambaforge\lib\site-packages\py4cytoscape-1.6.0-py3.10.egg\py4cytoscape\tables.py:502: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
```

I got this Warning in py4cytoscape 1.6.0 + Python 3.10.8.

If using `.items` is not too early, I will send the PR.
Let me know if you have any thoughts.

**Comment by bdemchak** [comment]
Fixed this in https://github.com/cytoscape/py4cytoscape/commit/70ef557f43cde6b11785628a8c10defa83319c98
