### ISSUE TITLE
select_nodes fails with comma in node name 

### ISSUE THREAD

**Issue by carissableker** [cytoscape/py4cytoscape#99]
E.g. node name is `A,B`

    p4c.network_selection.select_nodes(['A,B'], by_col="name", preserve_current_selection=False) 

does not work, but escaping the comma does:

    p4c.network_selection.select_nodes(['A\,B'], by_col="name", preserve_current_selection=False) 

Not a deal-breaking issue, but could perhaps be documented?

Version info:
    
    >>>p4c.cytoscape_version_info()    
    {'apiVersion': 'v1',
    'cytoscapeVersion': '3.8.1',
    'automationAPIVersion': '1.6.0',
    'py4cytoscapeVersion': '1.6.0'}

**Comment by bdemchak** [comment]
Thanks, Carissa, for finding this. I'll document it for the 1.7 release, which ought to be along in the next few weeks.
